"""Type stubs for aether_protocol.ephemeral_signer"""

# secp256k1 curve constants
P: int
N: int
Gx: int
Gy: int
A: int
B: int

class EphemeralSigner:
    def __init__(self, quantum_seed: int) -> None: ...
    @property
    def public_key_hex(self) -> str: ...
    @property
    def is_destroyed(self) -> bool: ...
    @property
    def sign_count(self) -> int: ...
    def sign_manifest(self, manifest: dict) -> dict: ...
    def verify(self, manifest: dict, signature: dict) -> bool: ...
    def destroy(self) -> dict: ...
