"""Type stubs for aether_protocol.terminal_ui"""

from typing import Any, Optional

_RICH_AVAILABLE: bool
__version__: str

class AetherConsole:
    def __init__(self, quiet: bool = False) -> None: ...
    @property
    def is_active(self) -> bool: ...
    def boot_banner(
        self,
        version: str = ...,
        seed_method: str = ...,
        log_path: str = ...,
        host: str = ...,
        port: int = ...,
    ) -> None: ...
    def show_seed_generating(self, method: str = ...) -> None: ...
    def show_seed_result(self, seed_result: Any) -> None: ...
    def show_seed_pool_status(self, pool_status: dict | None) -> None: ...
    def show_phase(
        self,
        phase: str,
        data: dict,
        signature: dict,
        order_id: Optional[str] = None,
    ) -> None: ...
    def show_phase_start(self, phase: str) -> None: ...
    def show_verification(self, result: dict, order_id: str = ...) -> None: ...
    def show_flow_complete(self, order_id: str) -> None: ...
    def status_line(self, message: str, style: str = ...) -> None: ...
    def rule(self, title: str = ..., style: str = ...) -> None: ...

def get_console(quiet: bool = False) -> AetherConsole: ...
