"""Type stubs for aether_protocol.verify"""

from .audit import AuditLog

class VerificationError(Exception): ...

class AuditVerifier:
    def verify_trade_flow(self, order_id: str, audit_log: AuditLog) -> dict: ...
    def detect_tampering(self, order_id: str, audit_log: AuditLog) -> dict: ...

class DisputeProofGenerator:
    def generate_proof(self, order_id: str, reason: str, audit_log: AuditLog) -> dict: ...
    def proof_authorization(self, order_id: str, audit_log: AuditLog) -> dict: ...
    def proof_execution_mismatch(self, order_id: str, audit_log: AuditLog) -> dict: ...
    def proof_settlement_mismatch(self, order_id: str, audit_log: AuditLog) -> dict: ...
    @staticmethod
    def to_exportable_json(proof: dict) -> str: ...
