"""
Stage I integration harness CLI.

Usage:
    python -m aether.harness.simulate \
        --tier pro --users 25 --days 30 \
        --persona-mix casual=0.6,power=0.35,abusive=0.05 \
        --seed 42 --out reports/

What runs:
    1. Minimal FastAPI app with uvt_router mounted (same pattern as
       tests/test_uvt_routes.py — avoids importing the full api_server,
       which has a pre-existing security.prompt_guard issue in this worktree).
    2. session_mgr shim maps per-user bearer tokens → emails.
    3. In-memory Supabase client seeded with plans + N users on the
       requested tier, injected into uvt_routes + Router.
    4. TokenAccountant's httpx.AsyncClient is patched to use a
       FakeAnthropicTransport — deterministic, never hits real Anthropic.
    5. Per-user traffic generated by UserProfile (persona-driven) day-by-day.
    6. Every call's response recorded. End-of-run reconciles /account/usage
       against the harness tally and emits CSV + Markdown.

Aether Systems LLC — Patent Pending
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import sys
import types
from contextlib import contextmanager
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from unittest.mock import MagicMock, patch

import httpx


# ─── Shim api_server.svc.session_mgr BEFORE importing uvt_routes ────────────
# uvt_routes imports `from api_server import svc` inside its auth dependency.
# We install a stand-in now so that import works without pulling the full
# backend (which has unrelated import issues in this worktree).
_session_registry: dict[str, str] = {}

_session_mgr = MagicMock()
_session_mgr.is_valid = MagicMock(side_effect=lambda t: t in _session_registry)
_session_mgr.get_username = MagicMock(side_effect=lambda t: _session_registry.get(t))
_stub_api_server = types.ModuleType("api_server")
_stub_api_server.svc = types.SimpleNamespace(session_mgr=_session_mgr)
sys.modules["api_server"] = _stub_api_server


# Now safe to import the UVT stack + our harness pieces
from fastapi import FastAPI  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from lib import token_accountant, uvt_routes  # noqa: E402
from lib.router import Router  # noqa: E402
from aether.harness.fake_anthropic import FakeAnthropicTransport  # noqa: E402
from aether.harness.in_memory_supabase import InMemorySupabaseClient  # noqa: E402
from aether.harness.report import CallRecord, build_markdown, write_csv  # noqa: E402
from aether.harness.user_simulator import (  # noqa: E402
    assign_personas, parse_persona_mix, UserProfile,
)


# ═══════════════════════════════════════════════════════════════════════════
# Harness context (everything wired up in one place)
# ═══════════════════════════════════════════════════════════════════════════


class HarnessContext:
    """Owns the TestClient + fake transport + supabase + user registry.

    Kept alive for the duration of a run. Patches applied at start(), undone
    at stop().
    """

    def __init__(self, *, seed: int):
        self.seed = seed
        self.supabase = InMemorySupabaseClient()
        self.transport = FakeAnthropicTransport(seed=seed, cache_hit_rate=0.5)
        self._token_to_email: dict[str, str] = {}
        self._patchers: list = []
        self._app = FastAPI()
        self._app.include_router(uvt_routes.uvt_router)
        self.client = TestClient(self._app)

    # ── lifecycle ──────────────────────────────────────────────────
    def start(self) -> None:
        uvt_routes.supabase_client = self.supabase
        uvt_routes.router_instance = Router(self.supabase)

        # TokenAccountant refuses to run without an Anthropic key — set a
        # fake. The transport below intercepts before anything leaves the
        # process, so the value is never actually transmitted.
        self._prev_key = os.environ.get("ANTHROPIC_API_KEY")
        os.environ["ANTHROPIC_API_KEY"] = "sk-ant-harness-fake"

        # Patch httpx.AsyncClient in the token_accountant namespace so
        # every call routes to our fake transport. We rebind the class
        # directly (simpler + more reliable than patch.object with
        # side_effect for a no-arg class call).
        transport = self.transport
        original = token_accountant.httpx.AsyncClient

        class _PatchedAsyncClient(original):  # type: ignore[misc]
            def __init__(self, *args, **kwargs):
                kwargs.pop("transport", None)
                super().__init__(*args, transport=transport, **kwargs)

        self._original_async_client = original
        token_accountant.httpx.AsyncClient = _PatchedAsyncClient

    def stop(self) -> None:
        for p in self._patchers:
            try: p.stop()
            except Exception: pass
        self._patchers.clear()
        # Restore original AsyncClient class
        if hasattr(self, "_original_async_client"):
            token_accountant.httpx.AsyncClient = self._original_async_client
        # Restore env
        if getattr(self, "_prev_key", None) is None:
            os.environ.pop("ANTHROPIC_API_KEY", None)
        else:
            os.environ["ANTHROPIC_API_KEY"] = self._prev_key
        uvt_routes.supabase_client = None
        uvt_routes.router_instance = None
        self._token_to_email.clear()
        _session_registry.clear()

    # ── user management ────────────────────────────────────────────
    def register_user(self, email: str, tier: str) -> tuple[str, str]:
        """Add a user to supabase + issue a bearer token. Returns (user_id, token)."""
        uid = self.supabase.db.add_user(email, tier)
        token = f"tok_harness_{uid[:12]}"
        _session_registry[token] = email
        self._token_to_email[token] = email
        return uid, token

    # ── call driver ────────────────────────────────────────────────
    def agent_run(
        self,
        *,
        token: str,
        prompt: str,
        load_hint: str,
        user_tier: str,
    ) -> tuple[int, dict]:
        """Fire one /agent/run. Pre-hints the fake transport with the true
        load so the classifier returns the ground-truth tier. Returns
        (status_code, body)."""
        # Each call triggers TWO Anthropic calls: classifier + orchestrator.
        # Both must reflect the same load for deterministic routing.
        self.transport.set_next_load(load_hint)

        resp = self.client.post(
            "/agent/run",
            json={"prompt": prompt},
            headers={"Authorization": f"Bearer {token}"},
        )
        try:
            body = resp.json()
        except Exception:
            body = {"_raw": resp.text[:500]}
        return resp.status_code, body

    def account_usage(self, token: str) -> dict:
        resp = self.client.get(
            "/account/usage",
            headers={"Authorization": f"Bearer {token}"},
        )
        return resp.json() if resp.status_code == 200 else {}


# ═══════════════════════════════════════════════════════════════════════════
# Call-record assembly (maps /agent/run responses → CallRecord rows)
# ═══════════════════════════════════════════════════════════════════════════


def _record_for_success(
    *, ctx: HarnessContext, user_id: str, email: str, day: int,
    tier: str, persona: str, load: str, body: dict,
) -> CallRecord:
    # The last FakeCallLog entries correspond to classifier + orchestrator.
    # We attribute underlying_cost_usd to whichever calls were made AFTER
    # the previous checkpoint. The transport log is append-only.
    # For bookkeeping simplicity, use the body totals and compute cost from
    # orchestrator model + its usage.
    orchestrator = body.get("orchestrator_model", "")
    classifier_load = body.get("qopc_load", body.get("load", "")) or load
    confidence = float(body.get("confidence") or 0)
    # /account/usage reports uvt_balances.total_uvt which accumulates from
    # BOTH classifier and orchestrator rpc_record_usage calls with their
    # ACTUAL token counts (not the router's char-estimate). The body's
    # classifier_uvt is a char-estimate, not the billed number — so we
    # read true values from the fake transport's call log below.
    orch_uvt = int(body.get("total_uvt") or 0)

    # Pull the last 2 transport calls for input/output token accounting.
    # (classifier then orchestrator). If only one, fall back.
    calls = ctx.transport.calls
    # The most recent orchestrator call — NOT a classifier call
    orch_call = None
    cls_call = None
    for c in reversed(calls):
        if c.load == "classifier" and cls_call is None:
            cls_call = c
        elif c.load != "classifier" and orch_call is None:
            orch_call = c
        if orch_call and cls_call:
            break

    input_tok = (orch_call.input_tokens if orch_call else 0)
    output_tok = (orch_call.output_tokens if orch_call else 0)
    cached_tok = (orch_call.cached_input_tokens if orch_call else 0)

    # True classifier UVT from the transport (what was actually written to
    # uvt_balances), not the router's char-estimate.
    classifier_uvt_true = 0
    if cls_call:
        classifier_uvt_true = max(
            0,
            (cls_call.input_tokens - cls_call.cached_input_tokens)
            + cls_call.output_tokens,
        )
    total_uvt = orch_uvt + classifier_uvt_true

    # Underlying cost = orchestrator + classifier COGS, summed
    from lib.model_registry import cost_usd_cents as _cost
    cost_cents = 0.0
    if orch_call:
        key = {"claude-haiku-4-5-20251001": "haiku",
               "claude-sonnet-4-6": "sonnet",
               "claude-opus-4-7": "opus"}.get(orch_call.model, "sonnet")
        cost_cents += _cost(key, orch_call.input_tokens, orch_call.output_tokens,
                            orch_call.cached_input_tokens)
    if cls_call:
        cost_cents += _cost("haiku", cls_call.input_tokens, cls_call.output_tokens,
                            cls_call.cached_input_tokens)

    return CallRecord(
        user_id=user_id, email=email, day=day, tier=tier, persona=persona, load=load,
        orchestrator_model=orchestrator, classifier_load=classifier_load,
        confidence=confidence,
        input_tokens=input_tok, output_tokens=output_tok,
        cached_input_tokens=cached_tok,
        uvt_charged=total_uvt,
        underlying_cost_usd=round(cost_cents / 100, 6),
        allowed=True, http_status=200,
        downgrade_reason=body.get("downgrade_reason") or "",
        reclassified=bool(body.get("reclassified")),
        detail_code="",
    )


def _record_for_denial(
    *, user_id: str, email: str, day: int,
    tier: str, persona: str, load: str,
    status: int, body: dict,
) -> CallRecord:
    detail = body.get("detail") or {}
    return CallRecord(
        user_id=user_id, email=email, day=day, tier=tier, persona=persona, load=load,
        orchestrator_model="", classifier_load="",
        confidence=0.0,
        input_tokens=0, output_tokens=0, cached_input_tokens=0,
        uvt_charged=0, underlying_cost_usd=0.0,
        allowed=False, http_status=status,
        downgrade_reason="", reclassified=False,
        detail_code=str(detail.get("error") or body.get("detail") or f"http_{status}"),
    )


# ═══════════════════════════════════════════════════════════════════════════
# Simulation driver
# ═══════════════════════════════════════════════════════════════════════════


def run_simulation(
    *,
    tier: str,
    users: int,
    days: int,
    persona_mix: dict[str, float],
    seed: int,
    out_dir: Path,
    quiet: bool = False,
) -> tuple[Path, Path, list[CallRecord]]:
    ctx = HarnessContext(seed=seed)
    ctx.start()

    try:
        # Seed users
        personas = assign_personas(users, persona_mix, seed=seed)
        user_records: list[tuple[str, str, str, str, UserProfile]] = []
        # (user_id, email, token, persona, profile)
        for i, p in enumerate(personas):
            email = f"user{i:04d}+{p}@harness.local"
            uid, token = ctx.register_user(email, tier)
            profile = UserProfile(email=email, tier=tier, persona=p, seed=seed + i)
            user_records.append((uid, email, token, p, profile))

        # Emit traffic
        records: list[CallRecord] = []
        for day in range(days):
            for uid, email, token, persona, profile in user_records:
                for call in profile.calls_for_day(day):
                    status, body = ctx.agent_run(
                        token=token, prompt=call.prompt,
                        load_hint=call.load, user_tier=tier,
                    )
                    if status == 200:
                        rec = _record_for_success(
                            ctx=ctx, user_id=uid, email=email, day=day,
                            tier=tier, persona=persona, load=call.load, body=body,
                        )
                    else:
                        rec = _record_for_denial(
                            user_id=uid, email=email, day=day,
                            tier=tier, persona=persona, load=call.load,
                            status=status, body=body,
                        )
                    records.append(rec)
            if not quiet and (day + 1) % 5 == 0:
                print(f"  day {day+1}/{days} · {len(records)} calls recorded")

        # End-of-run integration check: /account/usage must match our tally
        drift: list[str] = []
        for uid, email, token, persona, _ in user_records:
            usage = ctx.account_usage(token)
            if not usage:
                continue
            ours = sum(
                r.uvt_charged for r in records
                if r.user_id == uid and r.allowed
            )
            theirs = usage.get("monthly_uvt_used", -1)
            if abs(ours - theirs) > 0:
                drift.append(f"{email}: harness={ours} vs /account/usage={theirs}")

        # Persist artifacts
        out_dir.mkdir(parents=True, exist_ok=True)
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        csv_path = out_dir / f"margin-{ts}.csv"
        md_path = out_dir / f"margin-{ts}.md"

        write_csv(records, csv_path)
        users_per_tier = {tier: users}
        md = build_markdown(
            records=records, tier_filter=tier,
            users_per_tier=users_per_tier, days=days, seed=seed,
        )
        if drift:
            md += "\n## Integration drift (harness vs /account/usage)\n\n"
            for d in drift:
                md += f"- {d}\n"
            md += "\n"
        md_path.write_text(md, encoding="utf-8")

        return csv_path, md_path, records
    finally:
        ctx.stop()


# ═══════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="AetherCloud UVT margin harness")
    p.add_argument("--tier", required=True, choices=["free", "solo", "pro", "team"])
    p.add_argument("--users", type=int, default=10)
    p.add_argument("--days", type=int, default=30)
    p.add_argument(
        "--persona-mix", default="casual=0.6,power=0.35,abusive=0.05",
        help="comma-separated, e.g. 'casual=0.6,power=0.35,abusive=0.05'",
    )
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--out", default="reports/")
    p.add_argument("--quiet", action="store_true")
    return p.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = _parse_args(argv)
    mix = parse_persona_mix(args.persona_mix)
    out_dir = Path(args.out)
    if not args.quiet:
        print(f"[harness] AetherCloud UVT margin harness")
        print(f"  tier={args.tier} users={args.users} days={args.days}")
        print(f"  persona-mix={mix} seed={args.seed}")
        print(f"  writing to {out_dir}/")

    csv_path, md_path, records = run_simulation(
        tier=args.tier, users=args.users, days=args.days,
        persona_mix=mix, seed=args.seed, out_dir=out_dir, quiet=args.quiet,
    )

    if not args.quiet:
        print(f"\n[harness] OK - {len(records)} calls recorded")
        print(f"  CSV:  {csv_path}")
        print(f"  REP:  {md_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
